version: '3.7'

# environment
x-volumes: &server-volume
  SECRET_KEY: 'long-secret.key'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  POSTGRES_DB: 'blog_db'
  EMAIL_HOST: 'demo@gmail.com'
  EMAIL_PASS: 'demo_pass'
  DEBUG: 'true'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: nest_blog_server
    command: yarn start:dev
    # command: yarn start:debug # start debuging
    # command: yarn deploy:dev
    environment:
      <<: *server-volume
    ports:
      - '8000:8000'
      - '9229:9229' # debuging port
    networks:
      - backend-tier
    volumes:
      - ./:/server/
      - /server/node_modules
    depends_on:
      - db

  db:
    image: library/postgres:14
    container_name: nest_blog_db
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend-tier
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      <<: *server-volume

  worker:
    image: redis

volumes:
  postgres-db:
    driver: local

networks:
  backend-tier:
    driver: bridge
