version: '3.7'

# environment
x-volumes: &server-volume
  JWT_ALGORITHM: 'HS256'
  HOST: 'http://localhost:8000'

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: node_blog_server
    command: yarn start:dev
    env_file:
      - .env
    environment:
      <<: *server-volume
    ports:
      - '8000:8000'
    volumes:
      - ./:/server/
      - /server/node_modules
    depends_on:
      - db

  db:
    image: library/postgres:14
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend-tier
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis-server:
    image: redis

volumes:
  postgres-db:
    driver: local

networks:
  backend-tier:
    driver: bridge
